default_language_version:
  python: python
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
      stages: [commit]
    - id: end-of-file-fixer
      exclude: '^pytest/testdata'
      stages: [commit]
# -   repo: https://github.com/pycqa/flake8
#     rev: 5.0.4
#     hooks:
#       - id: flake8
#         stages: [commit]
